# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: c-linter-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-c-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
        
        
    # run linter on files
    - name: Run Lint with cpplint!
      run: cpplint --quiet --filter=-legal/copyright,-whitespace/line_length,-whitespace/braces --recursive */*
        
    
